name: OpenWrt Official Builder

on:
  workflow_dispatch:  # 手动触发构建

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: master  # 使用官方最新源码的 master 分支
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai  # 设置时区为上海时间

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Setup build environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install -y build-essential ccache libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc unzip python3-distutils file wget

    - name: Clone OpenWrt source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package dependencies
      run: |
        cd openwrt
        make defconfig
        make download -j8

    - name: Compile OpenWrt firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s

    - name: Check disk space usage
      run: df -hT

    - name: Upload compiled firmware
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true'
      with:
        name: OpenWrt_firmware_$(date +"%Y%m%d%H%M")
        path: openwrt/bin/targets/*/*

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: env.UPLOAD_RELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "openwrt-$(date +"%Y%m%d%H%M")"
        name: "OpenWrt $(date +"%Y-%m-%d %H:%M")"
        body: "Automated build of OpenWrt firmware from official source."
        files: openwrt/bin/targets/*/*

    - name: Clean up workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

    - name: Remove old releases
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true'
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
